filebeat.inputs:
  - type: log
    paths:
      - /var/log/openvpn-user-status.json
      # - /var/log/ovpn-ldap-auth.log
    # json.add_error_key: true
    # json.overwrite_keys: true
    # json.expand_keys: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOSTS}"]
  username: "${ELASTIC_USER}"
  password: "${ELASTIC_PASSWORD}"
  # index: "filebeat-%{[agent.version]}"

# output.console:
#   pretty: false

processors:
  - add_fields:
      target: ''
      fields:
        vm_hostname: 'OpenVPN Server'
  - drop_event:
      when: 
        contains:
          error.message: "Error decoding JSON: EOF"

setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}"










